"""Adicionando Salt

Revision ID: 34a7af3d0a25
Revises: dee6ff86ae16
Create Date: 2022-09-07 17:08:53.657657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a7af3d0a25'
down_revision = 'dee6ff86ae16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
