"""adicionando excerpt nos produtos

Revision ID: ccd78551dabb
Revises: 43a774bc6096
Create Date: 2022-09-08 07:50:06.450460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd78551dabb'
down_revision = '43a774bc6096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('excerpt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'excerpt')
    # ### end Alembic commands ###
