"""commit 2

Revision ID: dee6ff86ae16
Revises: e9449712b36e
Create Date: 2022-09-07 16:16:05.726666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee6ff86ae16'
down_revision = 'e9449712b36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###
